[package]
name = "learn-hal"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true
stm32f1xx-hal.workspace = true
panic-halt.workspace = true
