[package]
name = "led-blink"
version = "0.1.0"
edition.workspace = true
build = "../../build_share.rs"

[dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true
panic-halt.workspace = true
stm32f1xx-hal.workspace = true
